accounts/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('accounts/register/', views.register, name='register'),
    path('accounts/profile/', views.profile, name='profile'),
    re_path(r'^accounts/profile/(?P<id>\d+)$', views.guest_page, name='guest_page'),
    path('accounts/profile/edit', views.edit_profile, name='edit_profile'),
]

comments/urls.py
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    re_path(r'^post/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.post_comment, name='post_comment')
]

main/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.news, name='news_detail'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/like/$', views.like, name='like'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/dislike/$', views.dislike, name='dislike'),
    re_path(r'^category/(?P<slug>[-\w]+)/$', views.category, name='category'),
    path('search/', views.search, name='search'),
    path('create_post', views.create_post, name='create_post'),
]

news/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include(('main.urls', 'main'), namespace='news')),
    path('', include(('comments.urls', 'comments'), namespace='comments')),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
from django.db import models
from main.models import News
from django.contrib.auth.models import User
# Create your models here.
class Comment(models.Model):
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    text=models.TextField(max_length=300, verbose_name='Текст')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')
    news=models.ForeignKey(News, related_name='Комментарий', on_delete=models.CASCADE)
    parent=models.ForeignKey('self', on_delete=models.CASCADE, null=True, related_name='answer', blank=True)

    def get_child_comments(self):
        return Comment.objects.filter(parent=self.id)

main/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name='Название')
    slug = models.SlugField(max_length=50, unique=True, verbose_name='Слаг')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, related_name='child_category', blank=True)

    def __str__(self):
        return self.name
        
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self): 
        return reverse('news:category',
                       args=[self.slug])     

    def get_child_categories(self):
        return Category.objects.filter(parent=self.id)
    
class Tag(models.Model):
    name = models.CharField(max_length=25, verbose_name='Название')

    def __str__(self):
        return self.name
        
    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

class News(models.Model):
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    text = models.TextField(max_length=300, verbose_name='Текст')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    description = models.TextField(max_length=100, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='news_images/', verbose_name='Изображение', null=True)
    slug = models.SlugField(max_length=50, unique=True, verbose_name='Слаг')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    available = models.BooleanField(default=True, verbose_name='Доступно для просмотра')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, verbose_name='Категория')   
    likes = models.ManyToManyField(User, verbose_name='Лайки', related_name='likes', blank=True)
    dislikes = models.ManyToManyField(User, verbose_name='Дизлайки', related_name='dislikes', blank=True)
    post_views = models.PositiveIntegerField(verbose_name='Просмотры', default=0)
    tags = models.ManyToManyField(Tag, verbose_name='Теги', related_name='Tags')
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('news:news_detail',
                       args=[self.id, self.slug])        
    class Meta:
        verbose_name = 'Новости'
        verbose_name_plural = 'Новости'

comments/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Comment
from main.models import News
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Comment
from main.models import News
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


@login_required
def post_comment(request, id, slug):
    news = get_object_or_404(News, id=id, slug=slug)
    if request.method == 'POST':
        text = request.POST.get('comment_text')
        parent_id = request.POST.get('related_comment')
        if parent_id:
            related_comment = Comment.objects.get(id=parent_id)
            comment = Comment(author=request.user, text=text, news=news, parent=related_comment)
        else: 
            comment = Comment(author=request.user, text=text, news=news)

        comment.save()
    return redirect('main:news_detail', id=id, slug=slug)

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from slugify import slugify
from django.http import HttpResponse
from .models import News, Category
from accounts.models import Profile
from django.db.models import Q
from comments.models import Comment
from subscribe_bot import *
from social_django.models import UserSocialAuth
# Create your views here.

def index(request):
    news=News.objects.filter(available=True)
    return render(request, 'main/index.html', {'news': news})

def news(request, id, slug):
    news = get_object_or_404(News, id=id, slug=slug, available=True)
    comments = Comment.objects.filter(news=news)
    news.post_views += 1
    news.save()
    return render(request, 'main/news.html', {'news': news,
                                              'comments': comments})
    
def category(request, slug):
    category = get_object_or_404(Category, slug=slug)
    news = News.objects.filter(category=category)
    return render(request, 'main/category.html', {'category': category,
                                                  'news': news})

def search(request):
    query = request.GET.get('q')
    news = News.objects.filter(Q(title__icontains=query) | Q(category__name=query) | Q(tags__name=query))
    return render(request, 'main/index.html', {'news': news})

def create_post(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        text = request.POST.get('text')
        id = request.POST.get('category')
        image = request.FILES.get('image')
        slug = slugify(title)
        category = get_object_or_404(Category, id=id)
        news = News(title=title, text=text, description=description, category=category, image=image, author=request.user, slug=slug)
        news.save()
        news_detail = {'title': news.title,
                'description': news.description,
                'image': news.image.url,
                'category': news.category.name,
                'url': news.get_absolute_url()}
        subscribed_users = Profile.objects.filter(subscription_categories=category)
        telegram_ids = []
        for i in subscribed_users:
            telegram_ids.append(UserSocialAuth.objects.get(user=i.user).uid) 
        send_to_subscribers(news_detail, telegram_ids)
        created_post(news_detail)
        return redirect(news)
    return render(request, 'main/create_post.html')
    
def like(request, id, slug):
    user = request.user
    news = get_object_or_404(News, id=id, slug=slug)
    likes = news.likes.all()
    dislikes = news.dislikes.all()
    if user in likes:
        news.likes.remove(user)
    elif user in dislikes:
        news.likes.add(user)
        news.dislikes.remove(user)
    else:
        news.likes.add(user)
    return redirect('main:news_detail', id=id, slug=slug)

def dislike(request, id, slug):
    user = request.user
    news = get_object_or_404(News, id=id, slug=slug)
    dislikes = news.dislikes.all()
    likes = news.likes.all()
    if user in dislikes:
        news.dislikes.remove(user)
    elif user in likes:
        news.dislikes.add(user)
        news.likes.remove(user)
    else:
        news.dislikes.add(user)
    return redirect('main:news_detail', id=id, slug=slug)

main/templates/main/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href={% static 'css/style.css' %}>
</head>
<body class="d-flex flex-column h-100">
    {% include 'main/navbar.html' %}
    <main class="flex-shrink-0">
        <div class="container-fluid">{% block content %}{% endblock content %}</div>
    </main>
    {% include 'main/footer.html' %}
</body>
</html>

main/templates/main/comment.html
    {% if not comment.parent or reply %}
      <div {% if reply %} class="toast show ms-4" {% else %} class="toast show" {% endif %} role="alert" aria-live="assertive" aria-atomic="true">
          <div class="toast-header d-flex mb-3">
            <a href="{{child_comment.author.profile.get_absolute_url}}"><strong class="me-auto">{{comment.author}}</strong></a>
            {% if reply %}
            <small class="ms-3">в ответ <a href="{{comment.profile.get_absolute_url}}">{{comment.author}}</a></small>
            {% endif %}
            <small class="text-body-secondary ms-auto">{{comment.created}}</small>
          </div>
        <div class="toast-body d-flex justify-content-between" style="padding-top: 0;">
          {{comment.text}} 
          <p class="gap-1" style="margin-block-start: 0; margin-block-end: 0;">
            <a class="h6" data-bs-toggle="collapse" href="#comment{{comment.id}}" role="button" aria-expanded="false">
              Ответить
            </a>
          </p>
        </div>
      </div>
      {% if comment.get_child_comments|length %}
      {% for child_comment in comment.get_child_comments %}
      {%with comment=child_comment reply=True template_name="main/comment.html" %}
        {%include template_name%}
      {%endwith%}
      {% endfor %}
      {% endif %}
    {% endif %}
    <div class="collapse" id="comment{{comment.id}}" style="pointer-events: auto;">
      <form action="{% url 'comments:post_comment' id=news.id slug=news.slug %}" method="POST" style="width: 400;">
        <div class="mb-3">
          <input type="hidden" name="related_comment" value="{{comment.id}}">
          <label for="exampleFormControlTextarea1" class="form-label">Текст комментария</label>
          <textarea class="form-control" name="comment_text" id="exampleFormControlTextarea1" rows="2" style="resize: none;"></textarea>
        </div>
        <button type="submit" class="btn btn-primary btn-lg mb-5">Отправить комментарий</button>
        {% csrf_token %}
      </form>
    </div>  

main/templates/main/footer.html
<footer class="footer mt-auto py-3 bg-body-tertiary">
  <div class="container">
    <span class="text-body-secondary footer-text">Footer</span>
  </div>
</footer>

main/templates/main/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main:index' %}">Новости</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Админ-панель</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:create_post' %}">Опубликовать новость</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Категории
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          {% for category in categories %}
          {% if not category.parent %}
            {% if category.get_child_categories|length %}
              <li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" data-toggle="dropdown" href="{{category.get_absolute_url}}">{{category.name}}</a>
                <ul class="dropdown-menu">
                  {% for child_category in category.get_child_categories %}
                  <a class="dropdown-item" href="{{child_category.get_absolute_url}}">{{child_category.name}}</a>
                  {% endfor %}
                </ul>
              </li>
              {% else %}
              <li><a class="dropdown-item" href="{{category.get_absolute_url}}">{{category.name}}</a></li>
              {% endif %}
            {% endif %}
          {% endfor %}
          </ul>
        </li>
        {% comment %} <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Категории</a>
          <ul class="dropdown-menu">
            {% for category in categories %}
            {% if category.get_child_categories %}
            <a class="dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{category.name}}</a>
            <ul class="dropdown-menu">
              {% for child_category in category.get_child_categories %}
              <li>
                <a class="dropdown-item" href="{{category.get_absolute_url}}">{{category.name}}</a>
              </li>
              {% endfor %}
            </ul>
            {% else %} 
            <li>
              <a class="dropdown-item" href="{{category.get_absolute_url}}">{{category.name}}</a>
            </li>
            {% endif %}
            {% endfor %}
          </ul>
        </li> {% endcomment %}
      </ul>
      <form class="d-flex" role="search" action="{% url 'news:search' %}" method="GET">
        <input class="form-control me-2" type="search" name="q" placeholder="Поиск" aria-label="Search" />
        <button class="btn btn-outline-success me-5" type="submit">Поиск</button>
      </form>
      {% if not user.is_authenticated %}
      <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">Вход</a>
      <a href="{% url 'accounts:register' %}" class="btn btn-outline-primary me-2">Регистрация</a>
      {% else %}
      <a class="nav-link profile me-3" style="" href="{% url 'accounts:profile' %}">{{user.get_username}}</a>
      <a href="{% url 'logout' %}" class="btn btn-outline-danger me-2">Выход</a>
      {% endif %}
    </div>
  </div>
</nav> 

{% comment %} <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Navbar</a>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link 1</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <li><a class="dropdown-item" href="#">Action</a></li>
          <li><a class="dropdown-item" href="#">Another action</a></li>
          <li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" data-toggle="dropdown" href="#">Something else here</a>
            <ul class="dropdown-menu">
              <a class="dropdown-item" href="#">A</a>
              <a class="dropdown-item" href="#">b</a>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav> {% endcomment %}

main/templates/main/news.html
{% extends 'main/base.html' %}
{%load static%}
    {% block title %}{{news.title}}{% endblock title %}
    {% block content %}
    <p class="h1">{{news.title}}</p>
    <p><small>{{news.created}}</small></p>
    <p class="h5">{{news.description}}</p>
    <p class="h5 mb-5">{{news.text}}</p>
    <img class="news-image mb-3" src="{{news.image.url}}" alt="">
    <div class="d-flex justify-content-between under-news">
      <div class="mb-2">
        <a href="{% url 'main:like' id=news.id slug=news.slug %}">
          {% if user in news.likes.all %}
          <button type="button"  class="btn btn-primary">
            <svg class="mb-1 me-1" width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M20.2699 16.265L20.9754 12.1852C21.1516 11.1662 20.368 10.2342 19.335 10.2342H14.1539C13.6404 10.2342 13.2494 9.77328 13.3325 9.26598L13.9952 5.22142C14.1028 4.56435 14.0721 3.892 13.9049 3.24752C13.7664 2.71364 13.3545 2.28495 12.8128 2.11093L12.6678 2.06435C12.3404 1.95918 11.9831 1.98365 11.6744 2.13239C11.3347 2.29611 11.0861 2.59473 10.994 2.94989L10.5183 4.78374C10.3669 5.36723 10.1465 5.93045 9.86218 6.46262C9.44683 7.24017 8.80465 7.86246 8.13711 8.43769L6.69838 9.67749C6.29272 10.0271 6.07968 10.5506 6.12584 11.0844L6.93801 20.4771C7.0125 21.3386 7.7328 22 8.59658 22H13.2452C16.7265 22 19.6975 19.5744 20.2699 16.265Z" fill="#1C274C"/>
              <path fill-rule="evenodd" clip-rule="evenodd" d="M2.96767 9.48508C3.36893 9.46777 3.71261 9.76963 3.74721 10.1698L4.71881 21.4063C4.78122 22.1281 4.21268 22.7502 3.48671 22.7502C2.80289 22.7502 2.25 22.1954 2.25 21.5129V10.2344C2.25 9.83275 2.5664 9.5024 2.96767 9.48508Z" fill="#1C274C"/>
              </svg> {{news.likes.count}}
          </button>
          {% else %}
          <button type="button"  class="btn btn-primary disabled">
            <svg class="mb-1 me-1" width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M20.2699 16.265L20.9754 12.1852C21.1516 11.1662 20.368 10.2342 19.335 10.2342H14.1539C13.6404 10.2342 13.2494 9.77328 13.3325 9.26598L13.9952 5.22142C14.1028 4.56435 14.0721 3.892 13.9049 3.24752C13.7664 2.71364 13.3545 2.28495 12.8128 2.11093L12.6678 2.06435C12.3404 1.95918 11.9831 1.98365 11.6744 2.13239C11.3347 2.29611 11.0861 2.59473 10.994 2.94989L10.5183 4.78374C10.3669 5.36723 10.1465 5.93045 9.86218 6.46262C9.44683 7.24017 8.80465 7.86246 8.13711 8.43769L6.69838 9.67749C6.29272 10.0271 6.07968 10.5506 6.12584 11.0844L6.93801 20.4771C7.0125 21.3386 7.7328 22 8.59658 22H13.2452C16.7265 22 19.6975 19.5744 20.2699 16.265Z" fill="#1C274C"/>
              <path fill-rule="evenodd" clip-rule="evenodd" d="M2.96767 9.48508C3.36893 9.46777 3.71261 9.76963 3.74721 10.1698L4.71881 21.4063C4.78122 22.1281 4.21268 22.7502 3.48671 22.7502C2.80289 22.7502 2.25 22.1954 2.25 21.5129V10.2344C2.25 9.83275 2.5664 9.5024 2.96767 9.48508Z" fill="#1C274C"/>
              </svg> {{news.likes.count}}
          </button>
          {% endif %}
        </a>
        <a href="{% url 'main:dislike' id=news.id slug=news.slug %}">
          {% if user in news.dislikes.all %}
          <button type="button"  class="btn btn-danger">
            <svg class="mb-1 me-1" width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M20.2699 8.48505L20.9754 12.5648C21.1516 13.5838 20.368 14.5158 19.335 14.5158H14.1539C13.6404 14.5158 13.2494 14.9767 13.3325 15.484L13.9952 19.5286C14.1028 20.1857 14.0721 20.858 13.9049 21.5025C13.7664 22.0364 13.3545 22.465 12.8128 22.6391L12.6678 22.6856C12.3404 22.7908 11.9831 22.7663 11.6744 22.6176C11.3347 22.4539 11.0861 22.1553 10.994 21.8001L10.5183 19.9663C10.3669 19.3828 10.1465 18.8195 9.86218 18.2874C9.44683 17.5098 8.80465 16.8875 8.13711 16.3123L6.69838 15.0725C6.29272 14.7229 6.07968 14.1994 6.12584 13.6656L6.93801 4.27293C7.0125 3.41139 7.7328 2.75 8.59658 2.75H13.2452C16.7265 2.75 19.6975 5.17561 20.2699 8.48505Z" fill="#1C274C"/>
              <path fill-rule="evenodd" clip-rule="evenodd" d="M2.96767 15.2651C3.36893 15.2824 3.71261 14.9806 3.74721 14.5804L4.71881 3.34389C4.78122 2.6221 4.21268 2 3.48671 2C2.80289 2 2.25 2.55474 2.25 3.23726V14.5158C2.25 14.9174 2.5664 15.2478 2.96767 15.2651Z" fill="#1C274C"/>
              </svg> {{news.dislikes.count}}
          </button>
          {% else %}
          <button type="button"  class="btn btn-danger disabled">
            <svg class="mb-1 me-1" width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M20.2699 8.48505L20.9754 12.5648C21.1516 13.5838 20.368 14.5158 19.335 14.5158H14.1539C13.6404 14.5158 13.2494 14.9767 13.3325 15.484L13.9952 19.5286C14.1028 20.1857 14.0721 20.858 13.9049 21.5025C13.7664 22.0364 13.3545 22.465 12.8128 22.6391L12.6678 22.6856C12.3404 22.7908 11.9831 22.7663 11.6744 22.6176C11.3347 22.4539 11.0861 22.1553 10.994 21.8001L10.5183 19.9663C10.3669 19.3828 10.1465 18.8195 9.86218 18.2874C9.44683 17.5098 8.80465 16.8875 8.13711 16.3123L6.69838 15.0725C6.29272 14.7229 6.07968 14.1994 6.12584 13.6656L6.93801 4.27293C7.0125 3.41139 7.7328 2.75 8.59658 2.75H13.2452C16.7265 2.75 19.6975 5.17561 20.2699 8.48505Z" fill="#1C274C"/>
              <path fill-rule="evenodd" clip-rule="evenodd" d="M2.96767 15.2651C3.36893 15.2824 3.71261 14.9806 3.74721 14.5804L4.71881 3.34389C4.78122 2.6221 4.21268 2 3.48671 2C2.80289 2 2.25 2.55474 2.25 3.23726V14.5158C2.25 14.9174 2.5664 15.2478 2.96767 15.2651Z" fill="#1C274C"/>
              </svg> {{news.dislikes.count}}
          </button>
          {% endif %}
        </a>
      </div>
      <div>
        <small>{{news.post_views}}</small>
        <svg fill="#000000" width="20px" height="20px" viewBox="-3.5 0 32 32" version="1.1" xmlns="http://www.w3.org/2000/svg">
          <title>Просмотры</title>
          <path d="M12.406 13.844c1.188 0 2.156 0.969 2.156 2.156s-0.969 2.125-2.156 2.125-2.125-0.938-2.125-2.125 0.938-2.156 2.125-2.156zM12.406 8.531c7.063 0 12.156 6.625 12.156 6.625 0.344 0.438 0.344 1.219 0 1.656 0 0-5.094 6.625-12.156 6.625s-12.156-6.625-12.156-6.625c-0.344-0.438-0.344-1.219 0-1.656 0 0 5.094-6.625 12.156-6.625zM12.406 21.344c2.938 0 5.344-2.406 5.344-5.344s-2.406-5.344-5.344-5.344-5.344 2.406-5.344 5.344 2.406 5.344 5.344 5.344z"></path>
        </svg>
      </div>
    </div>
    <div class="toast-container position-static mb-5">
      {% for comment in comments %}
      {% include "main/comment.html" %}
      {% endfor %} 
    </div>
    {% if user.is_authenticated %}
    <form action="{% url 'comments:post_comment' id=news.id slug=news.slug %}" method="POST" style="width: 400px;">
          <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Текст комментария</label>
            <textarea class="form-control" name="comment_text" id="exampleFormControlTextarea1" rows="3" style="resize: none;"></textarea>
          </div>
          <button type="submit" class="btn btn-primary btn-lg mb-5">Отправить комментарий</button>
          {% csrf_token %}
    </form>
    {% endif %}
    {% endblock content %}